name: Release

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up GCC
          uses: egor-tensin/setup-gcc@v1
          with:
            version: latest
            platform: x64
        - name: Test
          run: |
            make all